#!/bin/bash
#PBS -l nodes=1:ppn=2,walltime=0:30:00
#PBS -N FSLBET

set -x
set -e

export input=$(jq -r .input config.json)
export fthresh=$(jq -r .fthreshold config.json)
mkdir -p ./work
copy_input=./work/$( basename ${input} )
cp ${input} ${copy_input}
input=${copy_input}

if [ "$(basename $input)" == "bold.nii.gz" ]; then
  #for func/task
  singularity exec -e docker://brainlife/fsl:6.0.1 bet $input masked.nii.gz -F -m -f $fthresh
else
  #for t1, t2, dwi, and flair
  singularity exec -e docker://brainlife/fsl:6.0.1 bet $input masked.nii.gz -R -m -f $fthresh
fi

#copy the input files as output (for func and dwi.. where we have things other than nii.gz)
rsync -av $(dirname $input)/ out
chmod +w out/$(basename $input)
cp masked.nii.gz out/$(basename $input)

mkdir -p mask
cp masked_mask.nii.gz mask/mask.nii.gz

#cat << EOF > product.json
#{
#    "brainlife": []
#}
#EOF

#"output": { "meta": { "Space": "$space" }, "tags": [ "space-$space"] },
#      {
#          "type": "image/png",
#          "name": "masked(x)",
#          "base64": "$(base64 -w 0 check.x.png)"
#      },
#      {
#          "type": "image/png",
#          "name": "masked(y)",
#          "base64": "$(base64 -w 0 check.y.png)"
#      },
#      {
#          "type": "image/png",
#          "name": "masked(y)",
#          "base64": "$(base64 -w 0 check.x.png)"
#      }

echo "all done"

